name: Clojure CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/cache@v2
      name: Cache lein dependencies
      env:
        cache-name: lein-dependencies
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('project.clj') }}
        restore-keys: ${{ runner.os }}-${{ env.cache-name }}

    - name: Install dependencies
      run: lein deps

    - name: Run tests
      run: lein test

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v2

    - uses: actions/cache@v2
      name: Cache lein dependencies
      env:
        cache-name: lein-dependencies
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('project.clj') }}
        restore-keys: ${{ runner.os }}-${{ env.cache-name }}

    - name: Install dependencies
      run: lein deps

    - name: Build uberjar
      run: lein uberjar

    - uses: actions/upload-artifact@v2
      with:
        name: winter-onboarding-2021
        path: target/winter-onboarding-2021-*-standalone.jar