name: Deploy to Heroku Production server

on:
  workflow_dispatch

jobs:
  deploy_production:
    name: Deploy to Production
    environment: Production
    runs-on: ubuntu-latest
    env:
      build_name: winter-onboarding-2021
      app_name: winter-onboarding-production
    steps:
    - name: Download build
      uses: actions/download-artifact@v2
      with:
        name: ${{ env.build_name }}
    - name: Install heroku java plugin
      run: heroku plugins:install java

    - name: Deploy build to production
      run: heroku deploy:jar ${{ env.build_name }}-*-standalone.jar --app ${{ env.app_name }}