name: Terraform plan

on:
  push:
    paths: "terraform/**"

defaults:
  run:
    working-directory: terraform

jobs:
  plan:
    environment: Staging
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_VAR_heroku_email: ${{ secrets.TF_VAR_HEROKU_EMAIL }}
      TF_VAR_heroku_api_key: ${{ secrets.TF_VAR_HEROKU_API_KEY }}
    steps:
    - uses: actions/checkout@v2
    - uses: hashicorp/setup-terraform@v1

    - name: Terraform init
      id: init
      run: terraform init

    - name: Terraform Validate
      id: validate
      run: terraform validate

    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color